version: '3.8'

services:

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    secrets:
      - MONGO_PASSWORD
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/MONGO_PASSWORD

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    secrets:
      - REDIS_PASSWORD
    command: >
      --requirepass /run/secrets/REDIS_PASSWORD

  api:
    build:
      dockerfile: Dockerfile
      context: "./Backend"
    volumes:
      - /app/node_modules
      - ./Backend:/app
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    ports:
      - "3001:3001"
    environment:
      REDIS_HOST: "redis"
      MONGO_HOST: "mongodb:27017"
      NODE_ENV: "PRODUCTION"

  client:
    build:
      dockerfile: Dockerfile
      context: ./Frontend
    volumes:
      - /app/node_modules
      - ./Frontend:/app
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3000:3000"

secrets:
  REDIS_PASSWORD:
    external: true
  MONGO_PASSWORD:
    external: true
