version: '3.8'

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./Backend/functions"
    volumes:
      - /app/node_modules
      - ./Backend/functions:/app

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./Frontend
    volumes:
      - /app/node_modules
      - ./Frontend:/app
