export const engineTriggers : { [key: string] : string[] } = {
  "unity": ["Unity WebGL Player", "unity-canvas", "unity-container"],
  "godot": ["GODOT_CONFIG"],
  "gameMaker: studio": ["GameMaker_Init"],
  "construct": ["--construct-scale", "Construct"],
  "unreal engine": ["UE4.js"],
  "gdevelop": ["gd.js", "gdjs"],
  "pico-8": ["p8_desktop", "p8_frame", "p8_", "PICO-8"],
  "pixijs": ["pixi.js"],
};

export const engines = [
  "GameMaker: Studio",
  "Bullet (Physics Engine)",
  "Clickteam Fusion",
  "Construct",
  "CryEngine",
  "GDevelop",
  "LÖVE",
  "PICO-8",
  "Unity",
  "Unreal Engine",
  "RPG Maker",
  "Godot",

  "AppGameKit",
  "ADLENGINE",
  "FlashDevelop",
  "EasyRPG",
  "Three.js",
  "TIC-80",
  "Torque 2D",
  "Lightweight Java Game Library",
  "Corona SDK",
  "ct.js",
  "Defold",
  "pygame",
  "Amulet",
  "Pixel Vision 8",
  "Elm",
  "Tiled",
  "Torque 3D",
  "Superpowers",
  "GB Studio",
  "DragonRuby GTK",
  "Rust",
  "Multimedia Fusion",
  "MonoGame",
  "RPG in a Box",
  "PixiJS",
  "Loom SDK",
  "Phaser",
  "ScummVM",
  "p5.js",
  "Haxe",
  "libGDX",
  "melonJS",
  "M.U.G.E.N",
  "PuzzleScript",
  "Ren'Py",
  "TyranoBuilder",
  "Twine",
  "raylib",
  "XNA",
  "Adventure Game Studio"
];