export const engines = [
  "GameMaker: Studio",
  "Bullet (Physics Engine)",
  "Clickteam Fusion",
  "Construct",
  "CryEngine",
  "GDevelop",
  "LÖVE",
  "PICO-8",
  "Unity",
  "Unreal Engine",
  "RPG Maker",
  "Godot",

  "AppGameKit",
  "ADLENGINE",
  "FlashDevelop",
  "EasyRPG",
  "Three.js",
  "TIC-80",
  "Torque 2D",
  "Lightweight Java Game Library",
  "Corona SDK",
  "ct.js",
  "Defold",
  "pygame",
  "Amulet",
  "Pixel Vision 8",
  "Elm",
  "Tiled",
  "Torque 3D",
  "Superpowers",
  "GB Studio",
  "DragonRuby GTK",
  "Rust",
  "Multimedia Fusion",
  "MonoGame",
  "RPG in a Box",
  "PixiJS",
  "Loom SDK",
  "Phaser",
  "ScummVM",
  "p5.js",
  "Haxe",
  "libGDX",
  "melonJS",
  "M.U.G.E.N",
  "PuzzleScript",
  "Ren'Py",
  "TyranoBuilder",
  "Twine",
  "raylib",
  "XNA",
  "Adventure Game Studio"
];
export const artCreation = [
  "3ds Max",
  "Adobe After Effects",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "Inkscape",
  "Aseprite",
  "Substance Painter",
  "Maya",
  "Cinema 4D",
  "MagicaVoxel",
  "Stencyl",
  "Piskel",
  "Krita",
  "GIMP",
  "Blender",
  "Paint.net",

  "Flickgame",
  "Crocotile 3D",
  "Wings3D",
  "Doodle Studio 95!",
  "SketchUp",
  "Sprytile",
  "Tilemancer",
  "Pixelmator",
  "Pixexix",
  "Clip Studio Paint",
  "GraphicsGale",
  "Corel Painter",
  "Pyxel Edit",
  "OGRE",
  "Processing",
  "Paint Tool SAI",
  "designer",
  "Kenney Studio",
  "ZBrush"
];
export const soundCreation = [
  "Audacity",
  "Bfxr",
  "Bitsy",
  "Bosca Ceoil",
  "Logic Pro",
  "FL Studio",
  "LMMS",

  "Renoise",
  "Box2D",
  "OpenFL",
  "MilkyTracker",
  "Chipmunk2D",
  "ChipTone"
];
